"""add offer_addons pricing fields

Revision ID: 3fb0510f5764
Revises: 
Create Date: 2026-01-06 01:06:37.138069

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '3fb0510f5764'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('job_addons', schema=None) as batch_op:
        batch_op.add_column(sa.Column('quantity', sa.Integer(), nullable=False, server_default='1'))
        batch_op.add_column(sa.Column('pricing_model', sa.Enum('fixed', 'per_unit', name='job_addon_pricing_model_enum'), nullable=False, server_default='fixed'))
        batch_op.add_column(sa.Column('category', sa.String(length=50), nullable=False, server_default='addon'))
        batch_op.add_column(sa.Column('duration_months', sa.Integer(), nullable=True))

    with op.batch_alter_table('offer_addons', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pricing_model', sa.Enum('fixed', 'per_unit', name='offer_addon_pricing_model_enum'), nullable=False, server_default='fixed'))
        batch_op.add_column(sa.Column('category', sa.String(length=50), nullable=False, server_default='addon'))
        batch_op.add_column(sa.Column('duration_months', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('offer_addons', schema=None) as batch_op:
        batch_op.drop_column('duration_months')
        batch_op.drop_column('category')
        batch_op.drop_column('pricing_model')

    with op.batch_alter_table('job_addons', schema=None) as batch_op:
        batch_op.drop_column('duration_months')
        batch_op.drop_column('category')
        batch_op.drop_column('pricing_model')
        batch_op.drop_column('quantity')

    # ### end Alembic commands ###
